spring:
  redis:
    database: 0
    host: 192.168.3.9
    port: 6379
    password: 123456
    timeout: 3600
    jedis:
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 20
        min-idle: 5