[dev.upload-run]
url = "http://192.168.1.2:10405/deploy/file/upload-run/"
p = "123456"
b = ".build.txt"
file = "target/jave-server-1.0.0.zip"
d = "unzip/jave-server"
c1 = "mkdir -p /data/apps/jave-server && mkdir -p backup/jave-server"
c2 = "[ -d /data/apps/jave-server ] && cp -r /data/apps/jave-server backup/jave-server/$(date +%Y%m%d_%H%M%S)"
c3 = "cp -r unzip/jave-server/* /data/apps/jave-server/"
c4 = "if [ $(docker ps -q -f name=jave-server) ]; then docker stop jave-server && docker rm -f jave-server; fi"
c5 = "cd /data/apps/jave-server/jave-server-1.0.0 && docker run -dit --name jave-server --restart=always --net=host -v $(pwd):/app -w /app -e TZ=Asia/Shanghai -e LANG=C.UTF-8 litongjava/jdk:8u391-stable-slim java -Xverify:none -cp ./config:./lib/*:./static com.litongjava.jave.server.JaveServerApp"
c = "docker ps |grep jave-server"
