[dev.upload-run]
url = "http://192.168.1.2:10405/deploy/file/upload-run/"
p = "123456"
b = ".build.txt"
file = "target/tio-boot-full-thin-demo01-1.0.0.zip"
d = "unzip/tio-boot-full-thin"
c1 = "mkdir -p /data/apps/tio-boot-full-thin"
c2 = "[ -d /data/apps/tio-boot-full-thin ] && cp -r /data/apps/tio-boot-full-thin backup/tio-boot-full-thin-backup-$(date +'%Y%m%d_%H%M%S')"
c3 = "cp -r unzip/tio-boot-full-thin/* /data/apps/tio-boot-full-thin/"
c4 = "if [ $(docker ps -q -f name=tio-boot-full-thin) ]; then docker stop tio-boot-full-thin && docker rm -f tio-boot-full-thin; fi"
c5 = "cd /data/apps/tio-boot-full-thin/tio-boot-full-thin-demo01-1.0.0 && docker run -dit --name tio-boot-full-thin --restart=always --net=host -v $(pwd):/app -w /app -e TZ=Asia/Shanghai -e LANG=C.UTF-8 litongjava/jdk:8u391-stable-slim java -Xverify:none -cp ./config:./lib/*:./static com.litongjava.full.thin.HelloApp"
c = "docker ps |grep tio-boot-full-thin"
