# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "imaginix-kimi-graph-api"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[checks]
  [checks.health_check]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/"
    port = 80
    timeout = "10s"
    type = "http"

